version: '3'

services:
  # MariaDB database
  database:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - app-network

  # WordPress Multisite
  wordpress:
    depends_on:
      - database
    image: wordpress:php8.0-fpm
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MARIADB_USER
      - WORDPRESS_DB_PASSWORD=$MARIADB_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app-network
      - faraday-network

  # Nginx webserver       
  webserver:
    depends_on:
      - wordpress
      - goaccess
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # WordPress
      - ./wordpress:/var/www/html
      # Nginx configuration files and SSL certs/keys
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      # websites
      - /home/cpc_admin/yurisearch/home:/var/yurisearch/
      - /home/kwalker/ai_site:/var/ai_site/
      # GoAccess
      - /home/cpc_admin/logs/wordpress:/var/log/nginx
      - ./goaccess/html:/srv/report
      - ./goaccess/data/access.conf:/etc/nginx/access.conf
    networks:
      - app-network

  # Certbot to renew SSL certificates
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ad7588@coventry.ac.uk --agree-tos --no-eff-email --force-renewal -d postdigitalcultures.org -d www.postdigitalcultures.org

  # GoAccess for web analytics
  # build and Nginx config from https://github.com/icamys/docker-goaccess-nginx
  goaccess:
    build:
       context: ./goaccess
       dockerfile: Dockerfile
       args:
          ALPINE_VERSION: 3.10.2
    restart: unless-stopped
    container_name: goaccess
    expose:
       - "7890"
    volumes:
       - ./goaccess/data:/srv/data
       - ./goaccess/html:/srv/report
       - /home/cpc_admin/logs/wordpress:/var/log/nginx/
       - ./goaccess/data/database:/tmp
    networks:
       - app-network

  # experiments with Tor services in Docker based on https://github.com/torservers/onionize-docker
  tor:
    container_name: tor
    image: torservers/onionize
    restart: always
    volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
       - app-network
       - faraday-network

  onion-nginx:
    container_name: onion-nginx
    image: nginx:latest
    volumes:
       # WordPress
       - ./wordpress:/var/www/html
       - ./nginx-conf/onion:/etc/nginx/conf.d
    environment:
       - ONIONSERVICE_NAME=onion-nginx
    depends_on:
       - wordpress
    networks:
       - faraday-network

volumes:
  mariadbdata:

networks:
  app-network:
     driver: bridge
  faraday-network:
    driver: bridge
    driver_opts:
       enable_ip_masquerade: "false"
