services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - APP_URL=$APP_URL
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_DATABASE=bookstackapp
      - BOOKSTACK_PORT=6875
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - docker_app-network

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
    networks:
      - docker_app-network

networks:
  docker_app-network:
    external: true
